### PR TITLE
Removed nil parentId's from span for compatibility with zipkin 1.1.4

### LINKED ISSUE #66: Unable to POST spans to zipkin-server 1.1.4
Unable to post spans to zipkin-server using current zipkin trace version.

zipkin-tracer: 0.18.1
zipkin-server: 1.1.4

Zipkin server responds with a 400 code and message body
`"Cannot decode spans due to IllegalArgumentException(Expected a string but was NULL at path $[0].parentId reading List<Span> from json: [{\"name\":\"get\",\"traceId\":\"9c88dbcdd6a4c1e6\",\"id\":\"9c88dbcdd6a4c1e6\",\"parentId\":null,\"annotations\":[{\"value\":\"sr\",\"timestamp\":1465341141243210,\"endpoint\":{\"ipv4\":\"127.0.1.1\",\"port\":4567,\"serviceName\":\"quote-server\"}},{\"value\":\"ss\",\"timestamp\":1465341141247275,\"endpoint\":{\"ipv4\":\"127.0.1.1\",\"port\":4567,\"serviceName\":\"quote-server\"}}],\"binaryAnnotations\":[{\"key\":\"http.uri\",\"value\":\"/\",\"endpoint\":{\"ipv4\":\"127.0.1.1\",\"port\":4567,\"serviceName\":\"quote-server\"}}],\"timestamp\":1465341141243187,\"duration\":4095,\"debug\":false}])\n",`

Removing 'parentId' when nil resolved the issue for me in AsyncJsonApiClient class (zipkin_json_tracer.rb).  Will make a pull request when I have run through benchmarks/tests etc.

### PR DESCRIPTION
**Pull request by singram**
resolves #66

### CODE REVIEW

**Comment by jcarres-mdsol** [comment]
The change is good but probably you'll need to change the Changelog and the version so we can create a new gem

**Comment by adriancole** [comment]
LGTM

**Comment by adriancole** [comment]
I think this should be merged anyway as it sends less bytes over the wire, but FWIW here's the relevant server change which would make previously deployed tracers not blow up https://github.com/openzipkin/zipkin/pull/1136

**Comment by adriancole** [comment]
zipkin 1.1.5 is out which should help previous versions of the tracer https://github.com/openzipkin/zipkin/releases/tag/1.1.5

**Comment by singram** [comment]
@adriancole Nice!  Changelog is now pushed if you still want to commit this.

**Comment by jcarres-mdsol** [comment]
@singram  also please change the version in `lib/zipkin-tracer/version.rb`

**Comment by singram** [comment]
@jcarres-mdsol Done.

**Pull request merged**
